name: Generate Sonic Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      # SVG-only version of the snake game
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: LESANF
          outputs: |
            dist/only-svg/github-contribution-grid-snake-sonic-dark.svg?color_snake=#2D9CDB&color_dots=#B3E0F2,#E0B3B3,#FF6B6B,#FFE364
            dist/only-svg/github-contribution-grid-snake-sonic.svg?color_snake=#2D9CDB&color_dots=#B3E0F2,#E0B3B3,#FF6B6B,#FFE364

      # Docker version of the snake game
      - uses: Platane/snk@v3
        with:
          github_user_name: LESANF
          outputs: |
            dist/docker/github-contribution-grid-snake-sonic-dark.svg?color_snake=#2D9CDB&color_dots=#B3E0F2,#E0B3B3,#FF6B6B,#FFE364
            dist/docker/github-contribution-grid-snake-sonic.svg?color_snake=#2D9CDB&color_dots=#B3E0F2,#E0B3B3,#FF6B6B,#FFE364

      # Ensure the generated files exist
      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/only-svg/github-contribution-grid-snake-kirby-dark.svg
          test -f dist/only-svg/github-contribution-grid-snake-kirby.svg
          test -f dist/docker/github-contribution-grid-snake-kirby-dark.svg
          test -f dist/docker/github-contribution-grid-snake-kirby.svg

      # Push the generated files to the designated branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
